# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2021-01-13 04:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseLoginInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=200, null=True, verbose_name='用户名')),
                ('user_password', models.CharField(default='111111', max_length=200, verbose_name='密码')),
                ('user_type_name', models.CharField(max_length=200, null=True, verbose_name='用户类型')),
                ('user_type_id', models.CharField(max_length=200, null=True, verbose_name='用户类型ID')),
                ('user_company', models.CharField(max_length=200, null=True, verbose_name='用户所在公司')),
                ('user_company_id', models.CharField(max_length=200, null=True, verbose_name='用户所在公司ID')),
            ],
        ),
        migrations.CreateModel(
            name='BasePayRateInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payrate_type', models.CharField(max_length=200, null=True, verbose_name='付款比例使用范围')),
                ('scales', models.FloatField(max_length=5, verbose_name='折扣率')),
                ('prepayPercent', models.FloatField(max_length=3, verbose_name='预付款比例')),
                ('deliveryPercent', models.FloatField(max_length=3, verbose_name='发货款比例')),
                ('arrivalPercent', models.FloatField(max_length=3, verbose_name='到货款比例')),
                ('installPercent', models.FloatField(max_length=3, verbose_name='安装款比例')),
                ('finishPercent', models.FloatField(max_length=3, verbose_name='结算款比例')),
                ('warrantyPercent', models.FloatField(max_length=3, verbose_name='质保金比例')),
            ],
        ),
        migrations.CreateModel(
            name='BaseTestInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host_name', models.CharField(max_length=50, verbose_name='分支名称')),
                ('host_port', models.CharField(max_length=50, verbose_name='测试环境')),
                ('host_mysql', models.CharField(max_length=50, verbose_name='使用数据库')),
            ],
        ),
    ]
