# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2021-01-13 05:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation_test', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='basetestinformation',
            name='base_catelog',
            field=models.CharField(default='抛光砖', max_length=20, verbose_name='商品所属行业'),
        ),
        migrations.AddField(
            model_name='basetestinformation',
            name='base_catelog_id',
            field=models.IntegerField(default=622, verbose_name='商品所属行业ID'),
        ),
        migrations.AddField(
            model_name='basetestinformation',
            name='base_price',
            field=models.FloatField(default=200.0, verbose_name='商品零售单价'),
        ),
    ]
