# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2021-01-13 06:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation_test', '0002_auto_20210113_1340'),
    ]

    operations = [
        migrations.AddField(
            model_name='basetestinformation',
            name='sale_id_1',
            field=models.IntegerField(default=0, max_length=20, verbose_name='订单中商品ID_1'),
        ),
        migrations.AddField(
            model_name='basetestinformation',
            name='sale_id_2',
            field=models.IntegerField(default=0, max_length=20, verbose_name='订单中商品ID_2'),
        ),
    ]
