# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2021-01-14 09:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation_test', '0003_auto_20210113_1406'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modulor', models.CharField(max_length=50, verbose_name='功能模块')),
                ('stop_state', models.CharField(max_length=50, verbose_name='停止状态')),
            ],
        ),
        migrations.AlterField(
            model_name='basetestinformation',
            name='sale_id_1',
            field=models.IntegerField(default=0, verbose_name='订单中商品ID_1'),
        ),
        migrations.AlterField(
            model_name='basetestinformation',
            name='sale_id_2',
            field=models.IntegerField(default=0, verbose_name='订单中商品ID_2'),
        ),
    ]
