# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2021-01-15 02:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation_test', '0004_auto_20210114_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baselogininformation',
            name='user_type_id',
            field=models.IntegerField(max_length=200, null=True, verbose_name='用户类型ID'),
        ),
    ]
