# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2021-01-13 04:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User_test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=200, null=True, verbose_name='用户')),
                ('user_password', models.CharField(max_length=200, verbose_name='密码')),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('record_status', models.CharField(default='正常', max_length=20, verbose_name='状态')),
                ('from_type', models.CharField(default='平台注册', max_length=20, verbose_name='来源')),
            ],
        ),
    ]
